language: cpp

sudo: required

addons:
  apt:
    packages:
      - docker-ce

env:
  - DIST=unstable

services:
  - docker

before_install:
  # install container
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull wrenchproject/wrench:${DIST};
      docker run -d -t --name=wrench wrenchproject/wrench:${DIST} bash;
      docker exec -it wrench git clone https://github.com/wrench-project/pegasus;
      docker exec -it wrench mkdir pegasus/build;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker exec -w /home/wrench/pegasus/build -it wrench cmake -DENABLE_BATSCHED=${BATSCHED} -DCMAKE_VERBOSE_MAKEFILE=ON ..;
      docker exec -w /home/wrench/pegasus/build -it wrench make all;
    fi

notifications:
  email:
    recipients:
      - wrench@mailman.isi.edu
    on_success: change
    on_failure: always
